### ISSUE TITLE
Add function error-handler

### ISSUE THREAD

**Issue by XVilka** [yuriy-chumak/ol#17]
To call it everytime error happens - to be able to handle it, instead of simple exit.
E.g. feeding the pointer of this handler to OL_new()

**Comment by yuriy-chumak** [comment]
Yes, this work is planned.
I'll notify after some code changes.

**Comment by yuriy-chumak** [comment]
Done in 680350796b61b822109c526e1749a4357163ff8e.

Now you can call OL_atexit(new_exit_handler) function with function "new_exit_handler" prototype like exit(int). Ol will call this new function instead of system exit().

OL_atexit() returns previous atexit function, so it can be used to build the chain of "exit" calls.

**Comment by XVilka** [comment]
Thank you!
