### ISSUE TITLE
OL_tb_start() - please add the parameter to load bytecode

### ISSUE THREAD

**Issue by XVilka** [yuriy-chumak/ol#21]
Currently I'm doing something like
```Makefile
some_example:
	$(OL_BIN) main.scm
	xxd -i main.bl > main_bytecode.h
	gcc -O0 -ggdb main.c $(OL_PATH)/src/olvm.c $(OL_PATH)/src/boot.c -std=c99 -ldl -DEMBEDDED_VM -DHAS_DLOPEN=1 -DHAS_PINVOKE=1 -o mytestapp \
	-Xlinker --export-dynamic $(OL_INCLUDE) -DSTANDALONE_APP
```
Where main.c contains code like:
```c
unsigned char *bootstrap = main_bl;
OL* ol = OL_new(bootstrap, NULL);
OL_eval(ol, 0, 0);
OL_free(ol);
```
Would be nice to be able to load this compiled bytecode of main.scm with OL_tb_start(). As far as I understand, there are some important functions in `talkback.lisp`. So I'd need to add them in the main.scm as well.

**Comment by yuriy-chumak** [comment]
Talkback API require interpreter bytecode to read and interpret text, that is sending over OL_tb_eval().
Text data is preferable way to send multiple data to the interpreter due to speed and size.

Can you describe your usecase in details? We can find the best way to do it.

But if you realy want to send bytecode instead of script source, the easiest way is translate bytecode into vector and send it as text. I can propose this "program" script:
`
(define (main)
   (print "my function result is")
   (print (+ 1 2 3))
)
(print "((fasl-decode (vector->list #" (fasl-encode main) ") (lambda () #t)))")
`
After executing this script produce precompiled text can be directly executed by OL_tb_eval().
Is it your case?

**Comment by yuriy-chumak** [comment]
talkback.lisp added to repo.

**Comment by XVilka** [comment]
For example. I have some script, compiled in the bytecode, then converting it in the static array, and want to load it using OL_tb_start.  It contains definitions of some functions, e.g.:
```
(define (myfunction buf1 buf1_size buf2 buf2_size) 
 ... do something and return a buffer
)
```
My case is to load this bytecode in "ol_scripts_init(char* myscripts_bytecode)", then to be able to call
the function `myfunction(char* buf1, int buf1_size, char* buf2, int buf2_size)`. And return a new buffer and its size. Or write the result in the 3rd buffer as a reference, I don't know what's easier.

**Comment by yuriy-chumak** [comment]
After lot of changes the embed interface goes better.
34457a8f3dc0322ccc3d88e2ef7749f7ce815364 change adding ability to run precompiled binary by olvm at runtime.
